### ISSUE TITLE
Leiningen Standalone JAR path disappears on restart

### ISSUE THREAD

**Issue by jgkite** [jenkinsci/leiningen-plugin#13]
When Jenkins is restarted, the value entered for **Leiningen Standalone JAR path** disappears, which has the effect of breaking all builds that depend on it. None of the other settings in `Jenkins > Manage Jenkins > Configure System` are lost.

* Jenkins version: 1.609
* leiningen-plugin version: 0.5.1 (maven ID org.spootnik:jenkins-leiningen:0.5.1)

I just noticed the note in the README: "For now this has to be installed manually." I believe I used the Jenkins Plugin Manager to install it; could that be the issue?

**Comment by sunggun-yu** [comment]
+1

**Comment by sunggun-yu** [comment]
@jgkite 
You can find another leiningen plugin 0.5.6 from available plugin tab.
it will work.

**Comment by sunggun-yu** [comment]
@jgkite 
and please remove old version

![image](https://cloud.githubusercontent.com/assets/817946/7356756/43e1ab04-ecf8-11e4-8fef-fb9dd3810426.png)

**Comment by jgkite** [comment]
Works so far! Thanks @sunggun-yu. :+1:
