### ISSUE TITLE
-Xbootclasspath automatically adds "a:" to front of argument.

### ISSUE THREAD

**Issue by jwhitlark** [jenkinsci/leiningen-plugin#7]
This seems like an old windows artifact.

instead of (on line 140)
args.add("-Xbootclasspath/a:" +  descriptor.getJarPath());

I think it should be 
args.add("-Xbootclasspath" +  descriptor.getJarPath());

But I'm not positive.

**Comment by aukevanleeuwen** [comment]
Not necessarily: `java -X`:

```
...
    -Xbootclasspath:<directories and zip/jar files separated by :>
                      set search path for bootstrap classes and resources
    -Xbootclasspath/a:<directories and zip/jar files separated by :>
                      append to end of bootstrap class path
    -Xbootclasspath/p:<directories and zip/jar files separated by :>
                      prepend in front of bootstrap class path
...
```

So basically the jarPath is appended to the boot classpath which is exactly what the `lein` script does if you'd install a stable release from http://leiningen.org/#install.
